### ISSUE TITLE
loading screen can get you stuck

### ISSUE THREAD

**Issue by BoogieHasFun** [Enginette/enginette#12]
idk you can go into a menu and get stuck on the loading so just uh fix it i guess

im tired

**Comment by DDev247** [comment]
it means the engine wasn't found or there was an error in the console

**Comment by DDev247** [comment]
added a text for that in `8138c002d18017a6f90be7edd57243218bcfecb8`

**Comment by DDev247** [comment]
There should be no issues now because of the new database 😄 
Also, new parameters will require just assigning them in the editor since it's pure JSON now. Updating the database will also be easy
