### ISSUE TITLE
Extremely unusable and annoying bug

### ISSUE THREAD

**Issue by quinnzaballa** [Enginette/enginette#16]
### When loading a tab besides engine and banks, causes loading screen infinitely.

When changing to tabs besides engine and banks will cause the link 

> y.app/engines/>>1<</edit/gen

**To**

> y.app/engines/>>undefined<</edit/gen

- Tried a different browser still the same
- I know this is a new thing but i would wish that this project will continue on no matter what
- The number specifies what engine project you are on

**Comment by pooriaahmadi** [comment]
fixed on RODS and BANKS
