### ISSUE TITLE
2 tabs not working

### ISSUE THREAD

**Issue by Abdullah-Ajeebi** [Enginette/enginette#27]
specifically "Cylinder Head" and "Distributor"

**Comment by DDev247** [comment]
what do you mean by "they dont work"

send a screenshot/screen recording if you can

**Comment by Abdullah-Ajeebi** [comment]
stuck in a loading screen and i dont know how to read the console.

anyways heres the screenshot
![Screenshot](https://user-images.githubusercontent.com/111107624/191991967-2fded279-9fb8-49a9-9255-c56b54e622fb.png)

**Comment by DDev247** [comment]
they should work but, if you have used enginette before 0.0.4 you need to clear the database
you can do that by pressing F12 then >>Application
![image](https://user-images.githubusercontent.com/87225187/192103124-8020de53-0046-426f-8367-cbed290649b7.png)
and then IndexedDB>enginette>delete database
![image](https://user-images.githubusercontent.com/87225187/192103195-f2ee1652-be61-41ab-b3ba-5faa4e27a64d.png)

**Comment by Abdullah-Ajeebi** [comment]
thanks
