### ISSUE TITLE
uh oh??

### ISSUE THREAD

**Issue by BoogieHasFun** [Enginette/enginette#29]
is this normal?
![image](https://user-images.githubusercontent.com/76754631/195224245-7d468e77-de23-4856-9e73-d1f028b7bfa1.png)

or is this happening because its not finished? 

info: app was run off of website

**Comment by Flyken271** [comment]
open inspect element, go to application, drop down local storage, clear local storage, refresh

**Comment by pooriaahmadi** [comment]
@Flyken271 Thanks for the response!
