### ISSUE TITLE
Improve the ability to understand the number charts.

### ISSUE THREAD

**Issue by ininja-ininja** [Enginette/enginette#38]
People will have difficulty understanding what certain charts in the engine editor mean. For example, what is that color chart in the Distributor tab? And the one in the Cylinder head? A title should be added above those charts so users know what it does without messing up their engine.
/

**Comment by TheMispeled** [comment]
the distributor one is prob timing. But idk for the others.

**Comment by DDev247** [comment]
Added the title in the new version.
