### ISSUE TITLE
f11 is not the inspect key on some browsers (feature request)

### ISSUE THREAD

**Issue by BoogieHasFun** [Enginette/enginette#42]
on the engine page, it says `WARNING: Your engines may have dissapeared as the database was changed. You can still view your old engine parameters by clicking F11 and viewing the application tab.`. on some browsers, like firefox, this is not true. i'm wondering if you could maybe check what browser the user is using, then adjust that message accordingly to the users browser so some people won't get confused :D
![image](https://github.com/Enginette/enginette/assets/76754631/9be82e44-9ac1-4349-aaea-148bd2ab4fe4)
thanks for making this btw
<3

**Comment by DDev247** [comment]
Fixed it, merge to the `main` branch will happen today when I add the fuel tab.
