### ISSUE TITLE
I get this error when exporting

### ISSUE THREAD

**Issue by Abdullah-Ajeebi** [Enginette/enginette#44]
Error occured: Traceback (most recent call last): File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async await CodeRunner( File "/lib/python311.zip/_pyodide/_base.py", line 363, in run_async coroutine = eval(self.code, globals, locals) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<exec>", line 643, in <module> File "<exec>", line 173, in generate File "<exec>", line 149, in generate_rod_journals AttributeError: 'NoneType' object has no attribute 'bank_angle'

**Comment by DDev247** [comment]
This error makes no sense. It shouldn't happen. It's saying the bank has no attribute `bank_angle` when in fact it has. Did you forget to add a bank?

**Comment by Abdullah-Ajeebi** [comment]
i have set the bank angles and now set the firing order to start at 0, yet no luck

**Comment by ininja-ininja** [comment]
Me too. I have the bank angle bug after making a new vehicle, trans and engine.

**Comment by DDev247** [comment]
Okay yes, I see what is happening.
When you add a bank this error happens.
Okay, so it turned out this error was happening because the `range` constructor in the Python script was not supplied with the begin index. Now it should work as intended.
