### ISSUE TITLE
No Attribute Bank Angle Error

### ISSUE THREAD

**Issue by ininja-ininja** [Enginette/enginette#49]
Even after the error bug fix, I still am getting the error! And I have the bank angle at 90 degrees. 
The delete button for engines doesn't work,and I have engines i want to delete.

**Comment by DDev247** [comment]
Your firing order must be incorrect. This is the only way I can reproduce this error.
About the delete button, I fixed it now.

**Comment by ininja-ininja** [comment]
Delete button works! 

But even checking the firing order, and having bank angles won't fix my error
